// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjXtIbYy6jYPVQk7a_MDac_GRBETlxuI',
    appId: '1:132540436443:web:54d704ad92960d3be061fe',
    messagingSenderId: '132540436443',
    projectId: 'praktikum-pbm-10',
    authDomain: 'praktikum-pbm-10.firebaseapp.com',
    storageBucket: 'praktikum-pbm-10.firebasestorage.app',
    measurementId: 'G-6S4YTGEC4N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyuwJ4X95p1UPO4gpgHdpXwLIqGcUDhM',
    appId: '1:132540436443:ios:7aeb0732df7bc9a8e061fe',
    messagingSenderId: '132540436443',
    projectId: 'praktikum-pbm-10',
    storageBucket: 'praktikum-pbm-10.firebasestorage.app',
    iosBundleId: 'com.example.flutterPbm10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyuwJ4X95p1UPO4gpgHdpXwLIqGcUDhM',
    appId: '1:132540436443:ios:7aeb0732df7bc9a8e061fe',
    messagingSenderId: '132540436443',
    projectId: 'praktikum-pbm-10',
    storageBucket: 'praktikum-pbm-10.firebasestorage.app',
    iosBundleId: 'com.example.flutterPbm10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdjXtIbYy6jYPVQk7a_MDac_GRBETlxuI',
    appId: '1:132540436443:web:42468a2278c1cb02e061fe',
    messagingSenderId: '132540436443',
    projectId: 'praktikum-pbm-10',
    authDomain: 'praktikum-pbm-10.firebaseapp.com',
    storageBucket: 'praktikum-pbm-10.firebasestorage.app',
    measurementId: 'G-J948GHGLLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlSL0JyakRD6l84Gz9zhrkNdRCC_4juYY',
    appId: '1:132540436443:android:9c9b8060628c8d8fe061fe',
    messagingSenderId: '132540436443',
    projectId: 'praktikum-pbm-10',
    storageBucket: 'praktikum-pbm-10.firebasestorage.app',
  );

}